import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Tree from './Tree.js'
import MyTree from './MyTree.js'
// import MyTreeView from './MyTreeView.js'
import DisplayChildren from './DisplayChildren.js'

class App extends Component {
  render() {
    var test = makeLocTree(mydata2);
    // console.log(test);
    return (
      <div className="App">
        <div className="App-header">
          <h2>My React Playground</h2>
        </div>

        <MyTree />

        <MyTree><MyTree /></MyTree>

        <DisplayChildren data={test} />
      </div>
    );
  }
}

export default App;

const data = {
    name: 'location',
    toggled: true,
    children: [
        {
            name: 'Canada',
            country: true,
            children: [
                { name: 'Quebec' },
                { name: 'Alberta' }
            ]
        },
        {
            name: 'US',
            loading: true,
            country: true,
            children: []
        },
        {
            name: 'Vietnam',
            children: [
                {
                    name: 'Hanoi',
                    children: [
                        { name: 'gateway1',
                          me:'huh' ,
                          children: [
                            {name: 'machine1'},
                            {name: 'machine2'}
                          ]
                        },
                        { name: 'gateway2' }
                    ]
                }
            ]
        }
    ],
};

const mydata = [ {"_id" : "MQkth2B86YQDHRPye", "licenseSystemID" : "E00-5579-A858-5F80", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-84dd79", "ipAddress" : "192.168.129.98", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 48, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "wuz4szHBFCp5yAcy8", "licenseSystemID" : "E00-2529-6A38-37EE", "gatewayIpAddress" : "184.71.250.14", "hostName" : "Userful-4a519b", "ipAddress" : "192.168.123.10", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1993.c67dcff-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 16, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-2529-6A38-37EE/ucc-cloud.html?sessionID=163DD2BC-65BB-44E0-B48E-5F595811DD8D", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "Has save login info", "onboardStations" : 1 }
,{ "_id" : "tymdKMP57GdpsQTLR", "licenseSystemID" : "E00-19BF-0F60-2107", "gatewayIpAddress" : "184.71.250.14", "hostName" : "quail", "ipAddress" : "192.168.120.8", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 9, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-19BF-0F60-2107/ucc-cloud.html?sessionID=FBBBD6E6-86EC-4FD5-9D2A-339C7A3A2592", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "This has login info saved", "onboardStations" : 1 }
,{ "_id" : "sbuKHvdBjhwahzW6d", "licenseSystemID" : "E00-5574-2643-81AD", "gatewayIpAddress" : "184.71.250.14", "hostName" : "chronos", "ipAddress" : "192.168.129.97", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 17, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "xjYQNhpHWRLyZ9iE8", "licenseSystemID" : "E00-5572-09AA-3B10", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-d85d65", "ipAddress" : "192.168.121.42", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1988.3e6340e-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 3, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-5572-09AA-3B10/ucc-cloud.html?sessionID=CA101B48-745F-40E8-A220-D5F62115A54D", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "Have saved login info", "onboardStations" : 1 }
,{ "_id" : "R8rt5oSzawCNQuuqj", "licenseSystemID" : "E00-2527-B709-A3EC", "gatewayIpAddress" : "184.71.250.14", "hostName" : "showcase", "ipAddress" : "192.168.137.96", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1995.c062643-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "hCwH6mSDuviSpkKiN", "licenseSystemID" : "E00-5560-5E62-5D0D", "gatewayIpAddress" : "184.71.250.14", "hostName" : "lisa", "ipAddress" : "192.168.123.8", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1978.e98c5cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 1, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-5560-5E62-5D0D/ucc-cloud.html?sessionID=974E9D5B-70E0-41C2-8A26-67D3DB9BD2DF", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "Have saved login info", "onboardStations" : 1 }
,{ "_id" : "aPdA295NJWgpSzsMM", "licenseSystemID" : "E00-C92F-EB3D-F7CC", "gatewayIpAddress" : "184.71.250.14", "hostName" : "duck", "ipAddress" : "192.168.136.96", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 9, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-C92F-EB3D-F7CC/ucc-cloud.html?sessionID=1499A5C0-D044-473D-BBF1-1DC7CFB0231C", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "aq5NhoEXYp4PCTtHi", "licenseSystemID" : "E00-BD33-97B0-897C", "gatewayIpAddress" : "184.71.250.14", "hostName" : "hu", "ipAddress" : "192.168.123.201", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "XSdxpDn5EoALekNNc", "licenseSystemID" : "E00-8DB8-EFAB-D4E7", "gatewayIpAddress" : "184.71.250.14", "hostName" : "Turing2", "ipAddress" : "192.168.128.97", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1995.c062643-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 10, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "4onuGBAXHZA6oTBPP", "licenseSystemID" : "E00-DD22-9E1B-A572", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-69c307", "ipAddress" : "192.168.132.90", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1900.5b474e8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "NMrWKMMJGstKMgStJ", "licenseSystemID" : "E00-0727-65A7-D15C", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-d5b729", "ipAddress" : "192.168.120.62", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "69JHKqmDh7haoinuE", "licenseSystemID" : "E00-1D7C-AA2C-0B7F", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-5e6d0a", "ipAddress" : "192.168.126.99", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1974.438e1b6-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "hvh7aXLwzuB37sEPr", "licenseSystemID" : "E00-0727-6576-9D6F", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-04fb1a", "ipAddress" : "192.168.120.145", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1981.ffcf0f3-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-0727-6576-9D6F/ucc-cloud.html?sessionID=71E677E0-E37E-486E-91BE-4508080BE05F", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "FHZw9jpykj8yivCfv", "licenseSystemID" : "E00-0727-652C-FA0D", "gatewayIpAddress" : "184.71.250.14", "hostName" : "mike-VM4", "ipAddress" : "192.168.120.234", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 2, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-0727-652C-FA0D/ucc-cloud.html?sessionID=8590D299-AFF6-4CEF-8557-748F67D12408", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "This Virtual machine does not work properly.\nAdded on Feb 14 by Mike:\nAfter updating the VM, it works fine.", "onboardStations" : 1 }
,{ "_id" : "3CwFvytzboN9sHxAz", "licenseSystemID" : "E00-F53B-79E4-748F", "gatewayIpAddress" : "184.71.250.14", "hostName" : "V", "ipAddress" : "192.168.129.99", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1991.4487f8b-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 4, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "Py6L9rTWNpf5sRfSn", "licenseSystemID" : "E00-5523-33C7-D43E", "gatewayIpAddress" : "199.244.85.65", "hostName" : "userful", "ipAddress" : "192.168.12.128", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1900.5b474e8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 2, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "US", "name" : "United States" }, "province" : { "countryCode" : "US", "provinceCode" : "Rhode Island", "name" : "Rhode Island", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "US", "provinceCode" : "Rhode Island", "city" : "Middletown" }, "gateway" : { "countryCode" : "US", "provinceCode" : "Rhode Island", "city" : "Middletown", "gatewayIpAddress" : "199.244.85.65", "gatewayName" : "199.244.85.65" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "YWbycT43tSZTF7vjg", "licenseSystemID" : "E00-5566-72ED-8DAD", "gatewayIpAddress" : "23.252.206.34", "hostName" : "userful-90", "ipAddress" : "10.0.1.162", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 19, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "US", "name" : "United States" }, "province" : { "countryCode" : "US", "provinceCode" : "Florida", "name" : "Florida", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "US", "provinceCode" : "Florida", "city" : "West Palm Beach" }, "gateway" : { "countryCode" : "US", "provinceCode" : "Florida", "city" : "West Palm Beach", "gatewayIpAddress" : "23.252.206.34", "gatewayName" : "23.252.206.34" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "WXirQvRzRcTndAqZY", "licenseSystemID" : "E00-15FE-39C9-0805", "gatewayIpAddress" : "184.71.250.14", "hostName" : "Turing", "ipAddress" : "192.168.128.98", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1995.c062643-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 10, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "8ZZkDxDAtMszpySSE", "licenseSystemID" : "E00-DDFB-EDFA-E1FD", "gatewayIpAddress" : "1.34.121.176", "hostName" : "0025aa", "ipAddress" : "192.168.1.14", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 7, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "TW", "name" : "Taiwan" }, "province" : { "countryCode" : "TW", "provinceCode" : "", "name" : "", "hasSubAdminLevel" : false }, "city" : { "countryCode" : "TW", "provinceCode" : "", "city" : "" }, "gateway" : { "countryCode" : "TW", "provinceCode" : "", "city" : "", "gatewayIpAddress" : "1.34.121.176", "gatewayName" : "1.34.121.176" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
];

const mydata2 = [

{ "_id" : "MQkth2B86YQDHRPye", "licenseSystemID" : "E00-5579-A858-5F80", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-84dd79", "ipAddress" : "192.168.129.98", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 48, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "wuz4szHBFCp5yAcy8", "licenseSystemID" : "E00-2529-6A38-37EE", "gatewayIpAddress" : "184.71.250.14", "hostName" : "Userful-4a519b", "ipAddress" : "192.168.123.10", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1993.c67dcff-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 16, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-2529-6A38-37EE/ucc-cloud.html?sessionID=163DD2BC-65BB-44E0-B48E-5F595811DD8D", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "Has save login info", "onboardStations" : 1 }
,{ "_id" : "tymdKMP57GdpsQTLR", "licenseSystemID" : "E00-19BF-0F60-2107", "gatewayIpAddress" : "184.71.250.14", "hostName" : "quail", "ipAddress" : "192.168.120.8", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 9, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-19BF-0F60-2107/ucc-cloud.html?sessionID=FBBBD6E6-86EC-4FD5-9D2A-339C7A3A2592", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "This has login info saved", "onboardStations" : 1 }
,{ "_id" : "sbuKHvdBjhwahzW6d", "licenseSystemID" : "E00-5574-2643-81AD", "gatewayIpAddress" : "184.71.250.14", "hostName" : "chronos", "ipAddress" : "192.168.129.97", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 17, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "xjYQNhpHWRLyZ9iE8", "licenseSystemID" : "E00-5572-09AA-3B10", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-d85d65", "ipAddress" : "192.168.121.42", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1988.3e6340e-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 3, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-5572-09AA-3B10/ucc-cloud.html?sessionID=CA101B48-745F-40E8-A220-D5F62115A54D", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "Have saved login info", "onboardStations" : 1 }
,{ "_id" : "R8rt5oSzawCNQuuqj", "licenseSystemID" : "E00-2527-B709-A3EC", "gatewayIpAddress" : "184.71.250.14", "hostName" : "showcase", "ipAddress" : "192.168.137.96", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1995.c062643-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "hCwH6mSDuviSpkKiN", "licenseSystemID" : "E00-5560-5E62-5D0D", "gatewayIpAddress" : "184.71.250.14", "hostName" : "lisa", "ipAddress" : "192.168.123.8", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1978.e98c5cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 1, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-5560-5E62-5D0D/ucc-cloud.html?sessionID=974E9D5B-70E0-41C2-8A26-67D3DB9BD2DF", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "Have saved login info", "onboardStations" : 1 }
,{ "_id" : "aPdA295NJWgpSzsMM", "licenseSystemID" : "E00-C92F-EB3D-F7CC", "gatewayIpAddress" : "184.71.250.14", "hostName" : "duck", "ipAddress" : "192.168.136.96", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 9, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-C92F-EB3D-F7CC/ucc-cloud.html?sessionID=1499A5C0-D044-473D-BBF1-1DC7CFB0231C", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "aq5NhoEXYp4PCTtHi", "licenseSystemID" : "E00-BD33-97B0-897C", "gatewayIpAddress" : "184.71.250.14", "hostName" : "hu", "ipAddress" : "192.168.123.201", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "XSdxpDn5EoALekNNc", "licenseSystemID" : "E00-8DB8-EFAB-D4E7", "gatewayIpAddress" : "184.71.250.14", "hostName" : "Turing2", "ipAddress" : "192.168.128.97", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1995.c062643-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 10, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "4onuGBAXHZA6oTBPP", "licenseSystemID" : "E00-DD22-9E1B-A572", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-69c307", "ipAddress" : "192.168.132.90", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1900.5b474e8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "NMrWKMMJGstKMgStJ", "licenseSystemID" : "E00-0727-65A7-D15C", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-d5b729", "ipAddress" : "192.168.120.62", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "69JHKqmDh7haoinuE", "licenseSystemID" : "E00-1D7C-AA2C-0B7F", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-5e6d0a", "ipAddress" : "192.168.126.99", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1974.438e1b6-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 6, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "hvh7aXLwzuB37sEPr", "licenseSystemID" : "E00-0727-6576-9D6F", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-04fb1a", "ipAddress" : "192.168.120.145", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1981.ffcf0f3-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-0727-6576-9D6F/ucc-cloud.html?sessionID=71E677E0-E37E-486E-91BE-4508080BE05F", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "FHZw9jpykj8yivCfv", "licenseSystemID" : "E00-0727-652C-FA0D", "gatewayIpAddress" : "184.71.250.14", "hostName" : "mike-VM4", "ipAddress" : "192.168.120.234", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 2, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-0727-652C-FA0D/ucc-cloud.html?sessionID=8590D299-AFF6-4CEF-8557-748F67D12408", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "This Virtual machine does not work properly.\nAdded on Feb 14 by Mike:\nAfter updating the VM, it works fine.", "onboardStations" : 1 }
,{ "_id" : "3CwFvytzboN9sHxAz", "licenseSystemID" : "E00-F53B-79E4-748F", "gatewayIpAddress" : "184.71.250.14", "hostName" : "V", "ipAddress" : "192.168.129.99", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1991.4487f8b-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 4, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "Py6L9rTWNpf5sRfSn", "licenseSystemID" : "E00-5523-33C7-D43E", "gatewayIpAddress" : "199.244.85.65", "hostName" : "userful", "ipAddress" : "192.168.12.128", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1900.5b474e8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 2, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "US", "name" : "United States" }, "province" : { "countryCode" : "US", "provinceCode" : "Rhode Island", "name" : "Rhode Island", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "US", "provinceCode" : "Rhode Island", "city" : "Middletown" }, "gateway" : { "countryCode" : "US", "provinceCode" : "Rhode Island", "city" : "Middletown", "gatewayIpAddress" : "199.244.85.65", "gatewayName" : "199.244.85.65" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "YWbycT43tSZTF7vjg", "licenseSystemID" : "E00-5566-72ED-8DAD", "gatewayIpAddress" : "23.252.206.34", "hostName" : "userful-90", "ipAddress" : "10.0.1.162", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 19, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "US", "name" : "United States" }, "province" : { "countryCode" : "US", "provinceCode" : "Florida", "name" : "Florida", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "US", "provinceCode" : "Florida", "city" : "West Palm Beach" }, "gateway" : { "countryCode" : "US", "provinceCode" : "Florida", "city" : "West Palm Beach", "gatewayIpAddress" : "23.252.206.34", "gatewayName" : "23.252.206.34" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "WXirQvRzRcTndAqZY", "licenseSystemID" : "E00-15FE-39C9-0805", "gatewayIpAddress" : "184.71.250.14", "hostName" : "Turing", "ipAddress" : "192.168.128.98", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1995.c062643-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.2", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 10, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : 1 }
,{ "_id" : "8ZZkDxDAtMszpySSE", "licenseSystemID" : "E00-DDFB-EDFA-E1FD", "gatewayIpAddress" : "1.34.121.176", "hostName" : "0025aa", "ipAddress" : "192.168.1.14", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 7, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "TW", "name" : "Taiwan" }, "province" : { "countryCode" : "TW", "provinceCode" : "", "name" : "", "hasSubAdminLevel" : false }, "city" : { "countryCode" : "TW", "provinceCode" : "", "city" : "" }, "gateway" : { "countryCode" : "TW", "provinceCode" : "", "city" : "", "gatewayIpAddress" : "1.34.121.176", "gatewayName" : "1.34.121.176" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "ZALMoMxKmQ96PWTZH", "licenseSystemID" : "E00-556C-BD70-9DF8", "gatewayIpAddress" : "1.34.121.176", "hostName" : "userful-02fb8c", "ipAddress" : "192.168.1.12", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 9, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "TW", "name" : "Taiwan" }, "province" : { "countryCode" : "CA", "provinceCode" : "", "name" : "", "hasSubAdminLevel" : false }, "city" : { "countryCode" : "CA", "provinceCode" : "", "city" : "" }, "gateway" : { "countryCode" : "TW", "provinceCode" : "", "city" : "", "gatewayIpAddress" : "1.34.121.176", "gatewayName" : "1.34.121.176" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "aTsmiGLviDN8vwJc3", "licenseSystemID" : "E00-5D73-4203-DFFC", "gatewayIpAddress" : "1.171.209.99", "hostName" : "useries-90b-vm", "ipAddress" : "192.168.0.109", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1905.b522ef8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 2, "unknownStations" : 0, "connectedStatus" : false, "country" : { "countryCode" : "TW", "name" : "Taiwan" }, "province" : { "countryCode" : "TW", "provinceCode" : "", "name" : "", "hasSubAdminLevel" : false }, "city" : { "countryCode" : "TW", "provinceCode" : "", "city" : "" }, "gateway" : { "countryCode" : "TW", "provinceCode" : "", "city" : "", "gatewayIpAddress" : "1.171.209.99", "gatewayName" : "1.171.209.99" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "WwAGEMrZnNf29yZmX", "licenseSystemID" : "E00-1D7C-AA4B-0976", "gatewayIpAddress" : "184.71.250.14", "hostName" : "AlphaGo", "ipAddress" : "192.168.127.98", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1989.f8e34ff-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 7, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-1D7C-AA4B-0976/ucc-cloud.html?sessionID=AF3795A7-5B84-4BE7-B657-4B471B43CC97", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "have saved login info", "onboardStations" : 1 }
,{ "_id" : "ozPMbiacWZq3oqG7G", "licenseSystemID" : "E00-5D73-4254-EEEE", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-26889b", "ipAddress" : "192.168.120.230", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1900.5b474e8-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : false, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "xkBj7JQDBZ3udtpKj", "licenseSystemID" : "E00-557F-4C5F-F204", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-2d9471", "ipAddress" : "192.168.120.40", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1967.2d2f240-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : false, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "", "onboardStations" : null }
,{ "_id" : "nxA2mpERq8fnPtsyx", "licenseSystemID" : "E00-5579-A858-9FB1", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-d85e88", "ipAddress" : "192.168.133.100", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1967.2d2f240-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboadStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "ks9zJ9bBBrcxLSFw5", "licenseSystemID" : "E00-EDB9-5FE8-E12A", "gatewayIpAddress" : "192.168.123.98", "hostName" : "EVA", "ipAddress" : "192.168.127.99", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboardStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "others", "name" : "others" }, "province" : { "countryCode" : "others", "provinceCode" : "others", "name" : "others", "hasSubAdminLevel" : false }, "city" : { "countryCode" : "others", "provinceCode" : "others", "city" : "others" }, "gateway" : { "countryCode" : "others", "provinceCode" : "others", "city" : "others", "gatewayIpAddress" : "192.168.123.98", "gatewayName" : "192.168.123.98" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "vD5G9Yi2JL2HH5Bnw", "licenseSystemID" : "E00-2529-6A4E-92D0", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-3cf4a5", "ipAddress" : "192.168.121.64", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1991.4487f8b-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboardStations" : 1, "networkStations" : 0, "usbStations" : 1, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "WtWN2HAxJHmpjc9Px", "licenseSystemID" : "E00-0596-2C52-31CB", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-2057be", "ipAddress" : "192.168.123.68", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboardStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : true, "UCCUrl" : "https://connect.userful.com/system/E00-0596-2C52-31CB/ucc-cloud.html?sessionID=E75DAFFA-8606-47C5-8519-900F6A075E9C", "machineCredential" : { "user" : "user", "password" : "1234" }, "note" : "" }
,{ "_id" : "JHu8YfbbvNoP8Ek3K", "licenseSystemID" : "E00-5572-09AB-E8EC", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-d98e99", "ipAddress" : "192.168.120.249", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboardStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : false, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "5ciJX8WRLmy67LSt4", "licenseSystemID" : "E00-556C-BD72-35ED", "gatewayIpAddress" : "184.71.250.14", "hostName" : "userful-005398", "ipAddress" : "192.168.123.215", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboardStations" : 1, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : true, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
,{ "_id" : "vM7RLY5ACNJfyphtb", "licenseSystemID" : "E00-793E-3131-AC48", "gatewayIpAddress" : "184.71.250.14", "hostName" : "vader", "ipAddress" : "192.168.136.98", "userfulVersion" : "9.0", "userfulBuildData" : "0.10.1970.3f797cb-1.el7", "linuxDistro" : "UEL", "linuxVersion" : "7.3", "onboardStations" : 0, "networkStations" : 0, "usbStations" : 0, "unknownStations" : 0, "connectedStatus" : false, "country" : { "countryCode" : "CA", "name" : "Canada" }, "province" : { "countryCode" : "CA", "provinceCode" : "Alberta", "name" : "Alberta", "hasSubAdminLevel" : true }, "city" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary" }, "gateway" : { "countryCode" : "CA", "provinceCode" : "Alberta", "city" : "Calgary", "gatewayIpAddress" : "184.71.250.14", "gatewayName" : "184.71.250.14" }, "cloudserver" : "connect.userful.com", "isAuthorized" : false, "UCCUrl" : "", "machineCredential" : { "user" : "", "password" : "" }, "note" : "" }
]

function makeLocTree(machineList) {
  var LocTree = {
    name:'Location',
    children:[]
  };
  machineList.forEach((machine)=>{

    var country = machine.country.name;
    var city = machine.city.city || 'unknown' ;
    var province = machine.province.name || 'unknown';
    var gateway = machine.gateway.gatewayIpAddress;
    var id = machine.licenseSystemID;

    var node = getArrayItemHaving(LocTree.children, country);
    // console.log(country);
    // console.log(LocTree);
    var nodeProvince = getArrayItemHaving(node.children, province) ;
      // console.log(nodeProvince);
    var nodeCity = getArrayItemHaving(nodeProvince.children, city);
    var nodeGateway = getArrayItemHaving(nodeCity.children, gateway);
    nodeGateway.children.push({name: machine.licenseSystemID});

  });

  return LocTree;

}

function getArrayItemHaving(myarray, name) {

  var res = {
    name: name,
    children:[]
  };
  if (myarray.length === 0) {
      console.log(name);
    myarray.push(res);
    // console.log(myarray[myarray.length-1]);
    return myarray[0];
  }

  for (var i = 0; i < myarray.length; i++) {
    if (myarray[i].name === name) {
      return myarray[i];
    }
  }

    myarray.push(res);
    // console.log(myarray[myarray.length-1]);
    return myarray[myarray.length-1];

}
